# Generated by Django 4.2.7 on 2023-11-22 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('joined_nb', models.PositiveIntegerField(default=0)),
                ('created_nb', models.PositiveIntegerField(default=0)),
                ('CA_buys', models.FloatField(default=0)),
                ('is_validated_money_man', models.BooleanField(default=False)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('CA_sales', models.FloatField(default=0)),
                ('avatar', models.ImageField(blank=True, default='avatar/default.jpg', null=True, upload_to='avatar/')),
                ('money_man_request_pending', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
