# Generated by Django 4.2.7 on 2023-11-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flow', '0002_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event/default.jpg', null=True, upload_to='event/'),
        ),
    ]
