# Generated by Django 4.2.7 on 2023-11-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flow', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_members',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
