# Generated by Django 4.2.7 on 2023-11-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flow', '0005_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinycart',
            name='client',
        ),
        migrations.RemoveField(
            model_name='tinycart',
            name='event',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='TinyCart',
        ),
    ]
